name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Cache node_modules
    - name: Cache ~/.npm
      uses: actions/cache@v2
      with:
        path: ~/.npm  # npm cache files are stored in `~/.npm` on Linux/macOS
        key: npm--${{ runner.os }}-Node12
    - name: cache node_modules/
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules--${{ runner.os }}-Node12-${{ hashFiles('yarn.lock') }}
    - name: cache packages/client/node_modules/
      uses: actions/cache@v2
      with:
        path: packages/client/node_modules
        key: packages/client/node-modules--${{ runner.os }}-Node12-${{ hashFiles('yarn.lock') }}
    - name: cache packages/common/node_modules/
      uses: actions/cache@v2
      with:
        path: packages/common/node_modules
        key: packages/common/node-modules--${{ runner.os }}-Node12-${{ hashFiles('yarn.lock') }}
    - name: cache packages/server/node_modules/
      uses: actions/cache@v2
      with:
        path: packages/server/node_modules
        key: packages/server/node-modules--${{ runner.os }}-Node12-${{ hashFiles('yarn.lock') }}
    - name: cache packages/server/src/service/cache
      uses: actions/cache@v2
      with:
        path: packages/server/src/service/cache
        key: packages/server/src/service/cache-2
    - name: Install Lerna
      run: npm install --global lerna
    - name: Boostrap
      run: yarn bootstrap

    # Back to doing real work
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
      env:
        CI: true
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        ALLOY_SANDBOX_API_KEY: ${{ secrets.ALLOY_SANDBOX_API_KEY }}
        ALLOY_SANDBOX_API_SECRET: ${{ secrets.ALLOY_SANDBOX_API_SECRET }}
